-- MySQL Script generated by MySQL Workbench
-- Tue Dec  6 17:55:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bong_da
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bong_da
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bong_da` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bong_da` ;

-- -----------------------------------------------------
-- Table `bong_da`.`DOI_BONG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bong_da`.`DOI_BONG` (
  `ID_Doi_Bong` CHAR(10) NOT NULL,
  `Ten_DB` VARCHAR(60) NULL,
  `San_Nha` VARCHAR(60) NULL,
  `Logo` VARBINARY(100) NULL,
  PRIMARY KEY (`ID_Doi_Bong`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bong_da`.`GIAI_DAU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bong_da`.`GIAI_DAU` (
  `ID_Giai_Dau` CHAR(10) NOT NULL,
  `Ten_GD` VARCHAR(60) NULL,
  `Ngay_Bat_Dau` DATETIME NULL,
  `Ngay_Ket_Thuc` DATETIME NULL,
  PRIMARY KEY (`ID_Giai_Dau`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bong_da`.`LOAI_BAN_THANG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bong_da`.`LOAI_BAN_THANG` (
  `ID_Loai_Ban_Thang` CHAR(10) NOT NULL,
  `Ten_LBT` VARCHAR(60) NULL,
  PRIMARY KEY (`ID_Loai_Ban_Thang`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bong_da`.`LICH_THI_DAU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bong_da`.`LICH_THI_DAU` (
  `ID_Lich_Thi_Dau` CHAR(10) NOT NULL,
  `Ngay_Thi_Dau` DATETIME NULL,
  `Gio_Thi_Dau` DATETIME NULL,
  `LICH_THI_DAUcol` DATETIME NULL,
  PRIMARY KEY (`ID_Lich_Thi_Dau`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bong_da`.`TRAN_DAU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bong_da`.`TRAN_DAU` (
  `ID_Tran_Dau` CHAR(10) NOT NULL,
  `Ti_So` VARCHAR(5) NULL,
  `Vong_Dau` INT NULL,
  `DOI_BONG_ID_Doi_Bong_1` CHAR(10) NOT NULL,
  `DOI_BONG_ID_Doi_Bong_2` CHAR(10) NOT NULL,
  `GIAI_DAU_ID_Giai_Dau` CHAR(10) NOT NULL,
  `LICH_THI_DAU_ID_Lich_Thi_Dau` CHAR(10) NOT NULL,
  PRIMARY KEY (`ID_Tran_Dau`, `DOI_BONG_ID_Doi_Bong_1`, `DOI_BONG_ID_Doi_Bong_2`, `GIAI_DAU_ID_Giai_Dau`, `LICH_THI_DAU_ID_Lich_Thi_Dau`),
  INDEX `fk_TRAN_DAU_DOI_BONG1_idx` (`DOI_BONG_ID_Doi_Bong_1` ASC) VISIBLE,
  INDEX `fk_TRAN_DAU_DOI_BONG2_idx` (`DOI_BONG_ID_Doi_Bong_2` ASC) VISIBLE,
  INDEX `fk_TRAN_DAU_GIAI_DAU1_idx` (`GIAI_DAU_ID_Giai_Dau` ASC) VISIBLE,
  INDEX `fk_TRAN_DAU_LICH_THI_DAU1_idx` (`LICH_THI_DAU_ID_Lich_Thi_Dau` ASC) VISIBLE,
  CONSTRAINT `fk_TRAN_DAU_DOI_BONG1`
    FOREIGN KEY (`DOI_BONG_ID_Doi_Bong_1`)
    REFERENCES `bong_da`.`DOI_BONG` (`ID_Doi_Bong`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRAN_DAU_DOI_BONG2`
    FOREIGN KEY (`DOI_BONG_ID_Doi_Bong_2`)
    REFERENCES `bong_da`.`DOI_BONG` (`ID_Doi_Bong`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRAN_DAU_GIAI_DAU1`
    FOREIGN KEY (`GIAI_DAU_ID_Giai_Dau`)
    REFERENCES `bong_da`.`GIAI_DAU` (`ID_Giai_Dau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRAN_DAU_LICH_THI_DAU1`
    FOREIGN KEY (`LICH_THI_DAU_ID_Lich_Thi_Dau`)
    REFERENCES `bong_da`.`LICH_THI_DAU` (`ID_Lich_Thi_Dau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bong_da`.`KET_QUA_TRAN_DAU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bong_da`.`KET_QUA_TRAN_DAU` (
  `Ten_Doi_Thang` VARCHAR(60) NULL,
  `Ten_Doi_Thua` VARCHAR(60) NULL,
  `TRAN_DAU_ID_Tran_Dau` CHAR(10) NOT NULL,
  `TRAN_DAU_DOI_BONG_ID_Doi_Bong_1` CHAR(10) NOT NULL,
  `TRAN_DAU_DOI_BONG_ID_Doi_Bong_2` CHAR(10) NOT NULL,
  `TRAN_DAU_GIAI_DAU_ID_Giai_Dau` CHAR(10) NOT NULL,
  INDEX `fk_KET_QUA_TRAN_DAU_TRAN_DAU1_idx` (`TRAN_DAU_ID_Tran_Dau` ASC, `TRAN_DAU_DOI_BONG_ID_Doi_Bong_1` ASC, `TRAN_DAU_DOI_BONG_ID_Doi_Bong_2` ASC, `TRAN_DAU_GIAI_DAU_ID_Giai_Dau` ASC) VISIBLE,
  PRIMARY KEY (`TRAN_DAU_ID_Tran_Dau`),
  CONSTRAINT `fk_KET_QUA_TRAN_DAU_TRAN_DAU1`
    FOREIGN KEY (`TRAN_DAU_ID_Tran_Dau` , `TRAN_DAU_DOI_BONG_ID_Doi_Bong_1` , `TRAN_DAU_DOI_BONG_ID_Doi_Bong_2` , `TRAN_DAU_GIAI_DAU_ID_Giai_Dau`)
    REFERENCES `bong_da`.`TRAN_DAU` (`ID_Tran_Dau` , `DOI_BONG_ID_Doi_Bong_1` , `DOI_BONG_ID_Doi_Bong_2` , `GIAI_DAU_ID_Giai_Dau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bong_da`.`GHI_BAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bong_da`.`GHI_BAN` (
  `ID_Ghi_Ban` CHAR(10) NOT NULL,
  `Thoi_Diem` DATETIME NULL,
  `LOAI_BAN_THANG_ID_Loai_Ban_Thang` CHAR(10) NOT NULL,
  `KET_QUA_TRAN_DAU_TRAN_DAU_ID_Tran_Dau` CHAR(10) NOT NULL,
  PRIMARY KEY (`ID_Ghi_Ban`, `LOAI_BAN_THANG_ID_Loai_Ban_Thang`, `KET_QUA_TRAN_DAU_TRAN_DAU_ID_Tran_Dau`),
  INDEX `fk_GHI_BAN_LOAI_BAN_THANG1_idx` (`LOAI_BAN_THANG_ID_Loai_Ban_Thang` ASC) VISIBLE,
  INDEX `fk_GHI_BAN_KET_QUA_TRAN_DAU1_idx` (`KET_QUA_TRAN_DAU_TRAN_DAU_ID_Tran_Dau` ASC) VISIBLE,
  CONSTRAINT `fk_GHI_BAN_LOAI_BAN_THANG1`
    FOREIGN KEY (`LOAI_BAN_THANG_ID_Loai_Ban_Thang`)
    REFERENCES `bong_da`.`LOAI_BAN_THANG` (`ID_Loai_Ban_Thang`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GHI_BAN_KET_QUA_TRAN_DAU1`
    FOREIGN KEY (`KET_QUA_TRAN_DAU_TRAN_DAU_ID_Tran_Dau`)
    REFERENCES `bong_da`.`KET_QUA_TRAN_DAU` (`TRAN_DAU_ID_Tran_Dau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bong_da`.`BANG_XEP_HANG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bong_da`.`BANG_XEP_HANG` (
  `ID_BXH` CHAR(10) NOT NULL,
  `Hang` INT NULL,
  `Thang` INT NULL,
  `Hoa` INT NULL,
  `Thua` INT NULL,
  `Hieu_So` VARCHAR(5) NULL,
  `DOI_BONG_ID_Doi_Bong` CHAR(10) NOT NULL,
  `GIAI_DAU_ID_Giai_Dau` CHAR(10) NOT NULL,
  PRIMARY KEY (`ID_BXH`, `DOI_BONG_ID_Doi_Bong`, `GIAI_DAU_ID_Giai_Dau`),
  INDEX `fk_BANG_XEP_HANG_DOI_BONG1_idx` (`DOI_BONG_ID_Doi_Bong` ASC) VISIBLE,
  INDEX `fk_BANG_XEP_HANG_GIAI_DAU1_idx` (`GIAI_DAU_ID_Giai_Dau` ASC) VISIBLE,
  CONSTRAINT `fk_BANG_XEP_HANG_DOI_BONG1`
    FOREIGN KEY (`DOI_BONG_ID_Doi_Bong`)
    REFERENCES `bong_da`.`DOI_BONG` (`ID_Doi_Bong`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BANG_XEP_HANG_GIAI_DAU1`
    FOREIGN KEY (`GIAI_DAU_ID_Giai_Dau`)
    REFERENCES `bong_da`.`GIAI_DAU` (`ID_Giai_Dau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bong_da`.`CAU_THU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bong_da`.`CAU_THU` (
  `ID-Cau_Thu` CHAR(10) NOT NULL,
  `Ten_CT` VARCHAR(60) NULL,
  `Loai_CT` VARCHAR(60) NULL,
  `Ghi_Chu` VARCHAR(60) NULL,
  `DOI_BONG_ID_Doi_Bong` CHAR(10) NOT NULL,
  PRIMARY KEY (`ID-Cau_Thu`, `DOI_BONG_ID_Doi_Bong`),
  INDEX `fk_CAU_THU_DOI_BONG_idx` (`DOI_BONG_ID_Doi_Bong` ASC) VISIBLE,
  CONSTRAINT `fk_CAU_THU_DOI_BONG`
    FOREIGN KEY (`DOI_BONG_ID_Doi_Bong`)
    REFERENCES `bong_da`.`DOI_BONG` (`ID_Doi_Bong`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bong_da`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bong_da`.`USER` (
  `ID_User` CHAR(10) NOT NULL,
  `Password` VARCHAR(30) NULL,
  `Email` VARCHAR(60) NULL,
  `Ten_User` VARCHAR(60) NULL,
  `Ngay_Sinh` DATETIME NULL,
  `Phone` INT NULL,
  PRIMARY KEY (`ID_User`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
